export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
//Pour insérer des outils ou styles globaux comme une navbar ou un thème sombre
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
