//métadonnées <head>
import type { Metadata } from 'next';

import RootLayout from "./root-layout";
import './globals.css';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Métadonnées côté serveur */}
        <meta name="description" content="Generated by Next.js" />
      </head>
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  )
}
