[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
bcrypt = "0.17.0"
diesel = { version = "2.2.7", features = ["postgres"] }
diesel_migrations = "2.2.0"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = "1.43.0"
